---
- name: Get latest build number from build server
  uri:
    url: "{{erp_installer_download_urls_api[erp_installer_environment]}}"
  register: builds_available
  when: not erp_build_number

- set_fact:
    # The [0] entry is 'latest', the [1] is the most recent build number.
    erp_build_number: "{{builds_available['json']['files'][1]['name']}}"
  when: not erp_build_number

# For backward compatibility
- set_fact:
    erp_latest_build: "{{erp_build_number}}"

- debug:
    msg: "Using {{erp_installer_distro}} {{erp_installer_environment}} build {{erp_build_number}}"

- name: Create local builds directory
  file:
    path: "./builds/{{erp_installer_distro}}-{{erp_installer_environment}}/{{erp_build_number}}"
    state: directory
- name: Save download paths
  set_fact:
    erp_image_paths:
      kernel: "./builds/{{erp_installer_distro}}-{{erp_installer_environment}}/{{erp_build_number}}/{{erp_image_remote_paths['kernel'] | basename}}"
      initrd: "./builds/{{erp_installer_distro}}-{{erp_installer_environment}}/{{erp_build_number}}/{{erp_image_remote_paths['initrd'] | basename}}"
- name: Download build locally
  get_url:
    url: "{{erp_installer_download_urls[erp_installer_environment]}}/{{erp_build_number}}/{{erp_image_remote_paths[item]}}"
    dest: "./builds/{{erp_installer_distro}}-{{erp_installer_environment}}/{{erp_build_number}}/{{erp_image_remote_paths[item] | basename}}"
  with_items:
    - "kernel"
    - "initrd"

- name: Set facts for mr-provisioner
  set_fact:
    mr_provisioner_kernel_description: "{{erp_installer_distro}}-installer {{erp_installer_environment}} build {{erp_build_number}}"
    mr_provisioner_initrd_description: "{{erp_installer_distro}}-installer {{erp_installer_environment}} build {{erp_build_number}}"
    mr_provisioner_kernel_path: "{{erp_image_paths['kernel']}}"
    mr_provisioner_initrd_path: "{{erp_image_paths['initrd']}}"
