---
- name: Get latest build number from Jenkins
  uri:
    url: "{{erp_debian_installer_jenkins_urls[erp_debian_installer_environment]}}"
  register: jenkins_build_info
  when: not erp_build_number
- set_fact:
    erp_build_number: "{{jenkins_build_info['json']['lastCompletedBuild']['number']}}"
  when: not erp_build_number

# For backward compatibility
- set_fact:
    erp_latest_build: "{{erp_build_number}}"

- debug:
    msg: "Using debian installer {{erp_debian_installer_environment}} build {{erp_build_number}}"

- name: Create local builds directory
  file:
    path: "./builds/debian-{{erp_debian_installer_environment}}/{{erp_build_number}}"
    state: directory
- name: Download build locally
  get_url:
    url: "{{erp_debian_installer_download_urls[erp_debian_installer_environment]}}/{{erp_build_number}}/debian-installer/arm64/{{item}}"
    dest: "./builds/debian-{{erp_debian_installer_environment}}/{{erp_build_number}}/{{item}}"
  with_items:
    - "initrd.gz"
    - "linux"
